### ISSUE TITLE
updating to last slidev version

### ISSUE THREAD

**Issue by carlobellettini** [twitwi/slidev-addon-ultracharger#19]
is it in program the update to the last slidev version?

Presently the last compatible version is 0.47.5 but slidev is at 0.49.3

I'm interested mainly to Anim (and InlineSvg) component(s) to animate SVGs.

Thanks

**Comment by twitwi** [comment]
Sorry I missed your message. Too much github notifications. Yes, I'll update it soon.

**Comment by twitwi** [comment]
@carlobellettini version 1.1.3 is adapted to slidev >=0.48.0 and is now published.
